### ISSUE TITLE
Change shop

### ISSUE THREAD

**Issue by NinaMol97** [keendelivery/api#2]
Hello, 

I was wondering if it is somehow possible to switch shops? My client has multiple webshops which use keendelivery on one account but I cannot find any way to set the adres label for your own company for each shipment, you can do this when you create a shipment manually however.

Thanks for the help!

Edit: I'll ask customer service as mentioned in the readme

**Comment by NinaMol97** [comment]
Reopened as a feature suggestion after having contact with customer support.

**Comment by wgriffioen** [comment]
This will be a feature in a new version of the API (v3) which will be available later this year. It's not possible to give an ETA yet.
